import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./comp/header";
import Footer from "./comp/footer";
import img from "../app/comp/imgs/bg1.png"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={`bg-[url("../app/comp/imgs/bg1.png")] bg-center text-white`}>
           <Header />
       
        
        <div>
           {children}
        </div>
        <hr className="text-neutral-500" />
        <Footer />
        </div>
          
       
      </body>
    </html>
  );
}
